### ISSUE TITLE
Unable to install via composer

### ISSUE THREAD

**Issue by klodeckl** [specialistaweb/textimage_size#1]
I had to install the extension via local repository because otherwise I get:
Could not find package specialistaweb/textimage-size. It was however found via repository search, which indicates a consistency issue with the repository.

**Comment by specialistaweb** [comment]
Hi Bernard

   thank you very much for your suggestion.

   Recently I updated the site the I removed the inclusion of text_image +ext, now all is working fine.

   About the composer there is some problem, I know, but now I have not time to adjust.

   thank you again

   cordially

   ALESSANDRO TUVERI


   --------------------------------------------------------
   http://www.specialistaweb.it
   Siti di qualità a costi contenuti, servizi professionali
   Portali per aziende, ecommerce, qualsiasi interazione
   Da "Bernhard Eckl" ***@***.***
   A "specialistaweb/textimage_size" ***@***.***
   Cc "Subscribed" ***@***.***
   Data Tue, 22 Mar 2022 12:08:59 -0700
   Oggetto [specialistaweb/textimage_size] Unable to install via composer (Issue #1)

   I had to install the extension via local repository because otherwise I get:
   Could not find package specialistaweb/textimage-size. It was however found via repository search, which indicates a consistency issue with the repository.

**Comment by klodeckl** [comment]
You’re welcome. 

I don’t use the extension now, at first I thought it would also adjust the calculated image sizes, but it doesn’t. But when I tested it also the css for e.g. col-md-3 was overwritten by the bootstrap package css, so the defined widths did not have an effect.

Meanwhile I have a good templating only solution (mixing fsc and bootstrap templates and use imagewidth field but still responsive images).

**Comment by specialistaweb** [comment]
HI the +ext is compatible only with the bootstrap_package, please tell me exactly what do you need, then I can modify it.

   Please verify if you loaded the library.

   If your styles overwrite the +ext styles I suppose there are some solution.

   I'm available to understand better the problem, send me more tech doc or examples



   --------------------------------------------------------
   http://www.specialistaweb.it
   Siti di qualità a costi contenuti, servizi professionali
   Portali per aziende, ecommerce, qualsiasi interazione
   Da "Bernhard Eckl" ***@***.***
   A "specialistaweb/textimage_size" ***@***.***
   Cc "Alessandro Tuveri" ***@***.***,"Comment" ***@***.***
   Data Tue, 22 Mar 2022 14:52:03 -0700
   Oggetto Re: [specialistaweb/textimage_size] Unable to install via composer (Issue #1)

   You’re welcome.

   I don’t use the extension now, at first I thought it would also adjust the calculated image sizes, but it doesn’t. But when I tested it also the css for e.g. col-md-3 was overwritten by the bootstrap package css, so the defined widths did not have an effect.

   Meanwhile I have a good templating only solution (mixing fsc and bootstrap templates and use imagewidth field but still responsive images).

**Comment by specialistaweb** [comment]
resolved
